//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Champions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Champions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character,,,
        ///STR,10,1,1
        ///DEX,10,1,2
        ///CON,10,1,1
        ///INT,10,1,1
        ///EGO,10,1,1
        ///PRE,10,1,1
        ///OCV,3,1,5
        ///DCV,3,1,5
        ///OMCD,3,1,3
        ///DMCV,3,1,3
        ///SPD,2,1,10
        ///PD,2,1,1
        ///ED,2,1,1
        ///REC,4,1,1
        ///END,20,5,1
        ///BODY,10,1,1
        ///STUN,20,2,1
        ///Run,12,1,1
        ///Leap,4,2,1
        ///Swim,4,2,1
        ///,,,
        ///Automaton,,,
        ///STR,10,1,1
        ///DEX,10,1,2
        ///CON,10,1,1
        ///INT,10,1,1
        ///PRE,10,1,1
        ///OCV,3,1,5
        ///DCV,3,1,5
        ///SPD,2,1,10
        ///PD,2,1,1
        ///ED,2,1,1
        ///REC,4,1,1
        ///END,20,5,1
        ///BODY,10,1,1
        ///STUN,20,2,1
        ///Run,12,1,1
        ///Leap,4,2,1
        ///Swim,4,2,1
        ///,,,
        ///Computer,,,
        ///DEX,10,1,2
        ///INT,10,1,1
        ///EGO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseCharacteristics {
            get {
                return ResourceManager.GetString("BaseCharacteristics", resourceCulture);
            }
        }
    }
}
